name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: rm -f package-lock.json && npm install
      - name: Check Formatting
        run: npx prettier --check . --ignore-unknown
      - name: Run tests
        run: npm test
      - name: Build package
        run: npm run build
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
